testing report

diff --git a/prismacloud/action.yml b/prismacloud/action.yml
--- a/prismacloud/action.yml
+++ b/prismacloud/action.yml
@@ -63,41 +63,48 @@ runs:
         image_name: ${{ inputs.IMAGE_NAME }}
         enable_report: ${{ inputs.ENABLE_REPORT }}
 
-    - name: Generate Vulnerabilities Report
-      if: ${{ inputs.ENABLE_REPORT == 'true' }}
-      id: report
-      shell: bash
-      working-directory: ${{ github.action_path }}
-      run: |
-        echo "Installing Python libraries for generating the report"
-        pip install -r requirements.txt
-        REPORT_FILE_NAME=prismacloud_scanning_results_$(date '+%m_%d_%Y').html
-        echo ""
-        echo "Generating HTML Report: $REPORT_FILE_NAME"
-        echo "REPORT_FILE_NAME=$REPORT_FILE_NAME" >>"${GITHUB_OUTPUT}"
-        python3 json2html.py -i ${{ steps.scan.outputs.results_file }} -o $REPORT_FILE_NAME
-        if [ -f "$REPORT_FILE_NAME" ]; then
-            echo "FILE_CREATED=true" >>"${GITHUB_OUTPUT}"
-            echo "FILE_CREATED=true"
-        else 
-            echo "FILE_CREATED=false" >>"${GITHUB_OUTPUT}"
-            echo "FILE_CREATED=false"
-        fi
-
-    - name: Archive Vulnerabilities Report
-      if: ${{ inputs.ENABLE_REPORT == 'true' && steps.report.outputs.FILE_CREATED == 'true' }}
-      uses: actions/upload-artifact@v3
+    - name: Upload scan result artifact
+      uses: actions/upload-artifact@v2
+      if: success() || failure()
       with:
-        name: wiz_vulnerabilities_secrets_report
-        path: ${{ github.action_path }}/${{ steps.report.outputs.REPORT_FILE_NAME }}
-        retention-days: ${{ inputs.REPORT_RETENTION_TIME }}
+        name: iac_scan_result
+        path: ${{ steps.scan.outputs.results_file }}
 
-    - name: Exit ${EXIT_CODE}, if prismacloud scan failed
-      if: ${{ steps.scan.outputs.PASS == 'false' }}
-      shell: bash
-      env:
-        exit_code: ${{ inputs.EXIT_CODE }}
-      run: |
-        echo "Wiz scan failed! Exiting with ${EXIT_CODE}." >&2
-        echo "See logs above for details." >&2
-        exit ${EXIT_CODE}
+    # - name: Generate Vulnerabilities Report
+    #   if: ${{ inputs.ENABLE_REPORT == 'true' }}
+    #   id: report
+    #   shell: bash
+    #   working-directory: ${{ github.action_path }}
+    #   run: |
+    #     echo "Installing Python libraries for generating the report"
+    #     pip install -r requirements.txt
+    #     REPORT_FILE_NAME=prismacloud_scanning_results_$(date '+%m_%d_%Y').html
+    #     echo ""
+    #     echo "Generating HTML Report: $REPORT_FILE_NAME"
+    #     echo "REPORT_FILE_NAME=$REPORT_FILE_NAME" >>"${GITHUB_OUTPUT}"
+    #     python3 json2html.py -i ${{ steps.scan.outputs.results_file }} -o $REPORT_FILE_NAME
+    #     if [ -f "$REPORT_FILE_NAME" ]; then
+    #         echo "FILE_CREATED=true" >>"${GITHUB_OUTPUT}"
+    #         echo "FILE_CREATED=true"
+    #     else 
+    #         echo "FILE_CREATED=false" >>"${GITHUB_OUTPUT}"
+    #         echo "FILE_CREATED=false"
+    #     fi
+
+    # - name: Archive Vulnerabilities Report
+    #   if: ${{ inputs.ENABLE_REPORT == 'true' && steps.report.outputs.FILE_CREATED == 'true' }}
+    #   uses: actions/upload-artifact@v3
+    #   with:
+    #     name: wiz_vulnerabilities_secrets_report
+    #     path: ${{ github.action_path }}/${{ steps.report.outputs.REPORT_FILE_NAME }}
+    #     retention-days: ${{ inputs.REPORT_RETENTION_TIME }}
+
+    # - name: Exit ${EXIT_CODE}, if prismacloud scan failed
+    #   if: ${{ steps.scan.outputs.PASS == 'false' }}
+    #   shell: bash
+    #   env:
+    #     exit_code: ${{ inputs.EXIT_CODE }}
+    #   run: |
+    #     echo "Wiz scan failed! Exiting with ${EXIT_CODE}." >&2
+    #     echo "See logs above for details." >&2
+    #     exit ${EXIT_CODE}
